### PR TITLE
Workercluster init fix

### PR DESCRIPTION
**Pull request by Nicholi**
Solves #321

A new controller to run specifically on workercluster.js after receiving the 'init' message. Fairly identical design to initController used by worker processes. Unlike initController no arguments are sent to the run() function.

### CODE REVIEW

**Comment by jondubois** [comment]
@Nicholi Thanks for that. Looks good at first glance. I'll test it out soon and merge it when I get the time.

**Comment by jondubois** [comment]
@Nicholi Thanks for following existing conventions that made it really easy for me.
After merging your PR, I renamed `initWorkerClusterController` to just `workerClusterController` - But it works exactly the same.

I think that the 'init...` controller should be unique because it's a special controller which runs on both worker and broker processes. Since this new controller is only run for the workerCluster process, it's OK to just call it `workerClusterController`.

I've released this in SC `v7.1.0`.

**Comment by happilymarrieddad** [comment]
+1

**Comment by Nicholi** [comment]
Excellent :)

**Pull request merged**
